package com.myelin.future.db.mybatis.dao;

import com.myelin.future.db.mybatis.dataobj.UserPost;
import com.myelin.future.db.mybatis.dataobj.UserPostExample;
import com.myelin.future.db.mybatis.dataobj.UserPostWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int countByExample(UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int deleteByExample(UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int deleteByPrimaryKey(Long postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int insert(UserPostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int insertSelective(UserPostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    List<UserPostWithBLOBs> selectByExampleWithBLOBs(UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    List<UserPost> selectByExample(UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    UserPostWithBLOBs selectByPrimaryKey(Long postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserPostWithBLOBs record, @Param("example") UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") UserPostWithBLOBs record, @Param("example") UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int updateByExample(@Param("record") UserPost record, @Param("example") UserPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int updateByPrimaryKeySelective(UserPostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(UserPostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table careme_post
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    int updateByPrimaryKey(UserPost record);
}