package com.myelin.future.db.mybatis.dataobj;

import java.util.Date;

public class UserPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.post_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.post_type
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.post_user_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long postUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.up_point
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long upPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.down_point
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long downPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.ctime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.utime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.parent_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.is_hidden
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer isHidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.tags
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.is_cryptonym
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer isCryptonym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.favorite_num
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer favoriteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_post.comment_num
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer commentNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.post_id
     *
     * @return the value of careme_post.post_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.post_id
     *
     * @param postId the value for careme_post.post_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.post_type
     *
     * @return the value of careme_post.post_type
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.post_type
     *
     * @param postType the value for careme_post.post_type
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setPostType(Integer postType) {
        this.postType = postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.post_user_id
     *
     * @return the value of careme_post.post_user_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getPostUserId() {
        return postUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.post_user_id
     *
     * @param postUserId the value for careme_post.post_user_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setPostUserId(Long postUserId) {
        this.postUserId = postUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.up_point
     *
     * @return the value of careme_post.up_point
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getUpPoint() {
        return upPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.up_point
     *
     * @param upPoint the value for careme_post.up_point
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setUpPoint(Long upPoint) {
        this.upPoint = upPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.down_point
     *
     * @return the value of careme_post.down_point
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getDownPoint() {
        return downPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.down_point
     *
     * @param downPoint the value for careme_post.down_point
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setDownPoint(Long downPoint) {
        this.downPoint = downPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.ctime
     *
     * @return the value of careme_post.ctime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.ctime
     *
     * @param ctime the value for careme_post.ctime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.utime
     *
     * @return the value of careme_post.utime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.utime
     *
     * @param utime the value for careme_post.utime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.parent_id
     *
     * @return the value of careme_post.parent_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.parent_id
     *
     * @param parentId the value for careme_post.parent_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.is_hidden
     *
     * @return the value of careme_post.is_hidden
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getIsHidden() {
        return isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.is_hidden
     *
     * @param isHidden the value for careme_post.is_hidden
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setIsHidden(Integer isHidden) {
        this.isHidden = isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.tags
     *
     * @return the value of careme_post.tags
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.tags
     *
     * @param tags the value for careme_post.tags
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setTags(Integer tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.is_cryptonym
     *
     * @return the value of careme_post.is_cryptonym
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getIsCryptonym() {
        return isCryptonym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.is_cryptonym
     *
     * @param isCryptonym the value for careme_post.is_cryptonym
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setIsCryptonym(Integer isCryptonym) {
        this.isCryptonym = isCryptonym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.favorite_num
     *
     * @return the value of careme_post.favorite_num
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getFavoriteNum() {
        return favoriteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.favorite_num
     *
     * @param favoriteNum the value for careme_post.favorite_num
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setFavoriteNum(Integer favoriteNum) {
        this.favoriteNum = favoriteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_post.comment_num
     *
     * @return the value of careme_post.comment_num
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_post.comment_num
     *
     * @param commentNum the value for careme_post.comment_num
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }
}