package com.myelin.future.db.mybatis.dataobj;

import java.util.Date;

public class UserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.nick
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.name
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.email
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.phone
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.password
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.user_desc
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String userDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.role
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.user_img
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String userImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.ctime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.utime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.last_login_time
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.is_deleted
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.is_disabled
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Integer isDisabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.tags
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private Long tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column careme_user_profile.user_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.id
     *
     * @return the value of careme_user_profile.id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.id
     *
     * @param id the value for careme_user_profile.id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.nick
     *
     * @return the value of careme_user_profile.nick
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.nick
     *
     * @param nick the value for careme_user_profile.nick
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.name
     *
     * @return the value of careme_user_profile.name
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.name
     *
     * @param name the value for careme_user_profile.name
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.email
     *
     * @return the value of careme_user_profile.email
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.email
     *
     * @param email the value for careme_user_profile.email
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.phone
     *
     * @return the value of careme_user_profile.phone
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.phone
     *
     * @param phone the value for careme_user_profile.phone
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.password
     *
     * @return the value of careme_user_profile.password
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.password
     *
     * @param password the value for careme_user_profile.password
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.user_desc
     *
     * @return the value of careme_user_profile.user_desc
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.user_desc
     *
     * @param userDesc the value for careme_user_profile.user_desc
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc == null ? null : userDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.role
     *
     * @return the value of careme_user_profile.role
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.role
     *
     * @param role the value for careme_user_profile.role
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.user_img
     *
     * @return the value of careme_user_profile.user_img
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.user_img
     *
     * @param userImg the value for careme_user_profile.user_img
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.ctime
     *
     * @return the value of careme_user_profile.ctime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.ctime
     *
     * @param ctime the value for careme_user_profile.ctime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.utime
     *
     * @return the value of careme_user_profile.utime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.utime
     *
     * @param utime the value for careme_user_profile.utime
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.last_login_time
     *
     * @return the value of careme_user_profile.last_login_time
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.last_login_time
     *
     * @param lastLoginTime the value for careme_user_profile.last_login_time
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.is_deleted
     *
     * @return the value of careme_user_profile.is_deleted
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.is_deleted
     *
     * @param isDeleted the value for careme_user_profile.is_deleted
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.is_disabled
     *
     * @return the value of careme_user_profile.is_disabled
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Integer getIsDisabled() {
        return isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.is_disabled
     *
     * @param isDisabled the value for careme_user_profile.is_disabled
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setIsDisabled(Integer isDisabled) {
        this.isDisabled = isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.tags
     *
     * @return the value of careme_user_profile.tags
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public Long getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.tags
     *
     * @param tags the value for careme_user_profile.tags
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setTags(Long tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column careme_user_profile.user_id
     *
     * @return the value of careme_user_profile.user_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column careme_user_profile.user_id
     *
     * @param userId the value for careme_user_profile.user_id
     *
     * @mbggenerated Mon Feb 09 17:44:49 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}